name: build

on:
  push:
   branches:
    - '*'
   tags:
    - '*'
  pull_request:
   branches:
   - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Initialize Energy Estimation
      uses: green-coding-berlin/eco-ci-energy-estimation@v1
      with:
        task: start-measurement
    - name: "Checkout repository"
      uses: actions/checkout@v3
    - name: Checkout Repo Measurement
      uses: green-coding-berlin/eco-ci-energy-estimation@v1
      with:
        task: get-measurement
        label: 'repository checkout'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Npm install
      run: npm ci
    - name: Npm build
      run: npm run build --if-present
    - name: Checkout Repo Measurement
      uses: green-coding-berlin/eco-ci-energy-estimation@v1
      with:
        task: get-measurement
        label: 'Npm activities'
    - name: Show Energy Results
      uses: green-coding-berlin/eco-ci-energy-estimation@v1
      with:
        task: display-results
