# To get a Slack Webhook URL, follow instruction here: https://api.slack.com/messaging/webhooks

name: "Notification regarding New Pull Request via Slack"
on:
  issue_comment: 
    - created
  
#  pull_request_target: 
#    types: [opened] 
jobs:
  notifyViaSlack:
    runs-on: ubuntu-latest
    steps:
      - uses: denolib/setup-deno@v2
        with:
         deno-version: v1.x
      - run: deno run --allow-net https://deno.land/x/cicd/notify-via-slack.ts ${{ secrets.SLACK_WEBHOOK_URL }} ${{ github.repository }} "Pull Request Created - ${{ github.event.pull_request.html_url }}"

# https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context
